export const GET_PLAYLISTS = 'GET_PLAYLISTS';
export const SET_PLAYLISTS =  'SET_PLAYLISTS';
export const GET_CURRENT_PLAYLIST_ID = 'GET_CURRENT_PLAYLIST_ID';
export const SET_CURRENT_PLAYLIST_ID =  'SET_CURRENT_PLAYLIST_ID';
export const GET_TRACKS = 'GET_TRACKS';
export const SET_TRACKS =  'SET_TRACKS';

